### PR TITLE
Merge TaskChampion repo into Taskwarrior

### PR DESCRIPTION
**Pull request by djmitche**
#### Description

This is the first of many steps for #2770.  It merges the TaskChampion repository, including its history, into this repository, with everything under `rust/`.  It then moves a few things to the top level (GitHub workflows, dependabot, etc. -- see the commits).

Obviously there's a lot more to do here, but I want to get this "first step" landed since GitHub is going to show it as a _huge_ mess of commits.  With this landed, subsequent commits can be reviewed as usual.  I also want to check that the workflows work.

When this lands, I'll archive the old taskchampion repo (and org) and indicate that development is occurring over here.

### CODE REVIEW

**Comment by djmitche** [comment]
Converted to a draft while I rearrange things a bit -- the GitHub actions don't support working directories, but I think I can work around that with Cargo workspaces.

**Comment by djmitche** [comment]
Hey, all green!

**Comment by djmitche** [comment]
btw I think this will require an admin to merge (only "Rebase and Merge" is enabled, and this can't be rebased)

**Comment by tbabej** [comment]
I love that this preserves the commit history. I'll work on merging this in.

**Review by tbabej — APPROVED** [review]

**Comment by ryneeverett** [comment]
> When this lands, I'll archive the old taskchampion repo (and org) and indicate that development is occurring over here.

@djmitche Looks like you archived taskchampion without indicating that it was merged into taskwarrior.

**Comment by tbabej** [comment]
There is a reference in the [discussions section of the repo](https://github.com/taskchampion/taskchampion/discussions/360).

**Comment by djmitche** [comment]
That's a good point, though -- I added a note to the README.

**Pull request merged**
