### PR TITLE
Remove 'sync' from default verbose flags

### LINKED ISSUE #3297: 3.x always warns that sync is required
From @jschleus in #3295:
> the new task command outputs always "There are XX local changes.  Sync required.".

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #3297 (except for folks who have an explicit "verbose" in their config, but they can adjust)

### CODE REVIEW

**Review by ryneeverett — APPROVED** [review]
I hadn't realized that `verbose=on` is the default which makes this a tougher decision -- ideally sync messages would be included in verbose output and the default would be off.

Maybe we should add to the synchronization documentation a recommendation to enable sync output in configuration? Any user using the sync support should probably have this enabled, right?

**Comment by ryneeverett** [comment]
In fact, maybe this output could be automatically included if sync options are configured?

**Comment by djmitche** [comment]
I don't actually think this particular message is that useful -- I've certainly turned it off locally, and I do use sync (but do so on a crontask).

But, including it when sync options are configured seems a good middle-ground.

**Comment by djmitche** [comment]
Updated to only remind if non-local sync is set up.

**Review by ryneeverett — COMMENTED** [review]
1. If you're using `sync.local.server_dir` don't you still want these messages?
2. Maybe the benefit of automatically making the smart choice here is worth it, but it seems like the logic here is liable to get out of sync (no pun) with the sync configuration options. As the sync options grow over time I don't see anyone thinking to update this logic. That's a non-issue if we manage this through the verbosity flags.

**Comment by djmitche** [comment]
As I said earlier, I don't really see the value to this at all, but certainly not for local sync.

I suspect every "real" sync option will use an encryption secret, so this seems reasonably safe. I'm not sure what alternative you're suggesting -- the earlier draft of this PR did manage it through verbosity settings.

**Comment by ryneeverett** [comment]
Isn't the point of this to remind people to run `task sync`? You still need to do that if you're using local sync.

**Comment by ryneeverett** [comment]
I was suggesting that the earlier draft might have been advantageous over this one because it managed it through verbosity settings. If the value of these messages is questionable, turning them off completely unless users opt-in seems reasonable.

On the other hand, the current version seems to restore the tw-2 behavior of only giving these messages if sync settings are configured. If you prefer to take this more conservative approach I have no objection.

> In fact, maybe this output could be automatically included if sync options are configured?

To clarify, I now see that you've implemented this suggestion of mine. I'm now questioning whether it's really a good idea.

**Comment by djmitche** [comment]
I think this was distracting for people using local sync (whether intentionally or not), but still useful for those setting up remote/cloud sync. Or to put it another way, your suggestion was a good one, and I agree.

**Pull request merged**
