### PR TITLE
add targets for individual tests

### PR DESCRIPTION
**Pull request by djmitche**
This means you can do `make -Cbuild verbose.test` and it will run just that test.

cc @felixschurk - WDYT?

### CODE REVIEW

**Review by ryneeverett — COMMENTED** [review]
This feature doesn't seem very useful without documentation.

**Comment by djmitche** [comment]
Good point - docs added!

**Review by ryneeverett — APPROVED** [review]

**Comment by felixschurk** [comment]
Hei, sorry can not to deeply look into it right now as I am on the road. I will have a proper look on Tuesday. :)

But I do think if we want individual targets it's then better to go with ctest.

Which adds an individual target for every test in an more unique way (no need for custom commands).

I played around with it a few days ago already, one can see it in this branch https://github.com/felixschurk/taskwarrior/tree/ctest-as-test-runner.

Maybe check it out and run
```sh
cmake -S . -B build
cmake --build build
cmake --build build -t build_test
ctest --test-dir build/test
```
if I have it right this would then build and the second run the tests/all test.
Of course you can add the `-j <# cores> flag to both build and ctest commands to run it in parallel.
It will also show how/why the test failed (e.g. some fail with segmentation fault)

For a specific test one could do
```sh
ctest --test-dir build/test -R <name of test>
````
I prefixed the cpp test with `unittest_` and the python test with `integrationtest_`.


#724 was made a "decision" against ctest, however I think there is also a small misunderstanding about ctest, it does not replace a test suite - only the way how the suite is run, e.g. it would replace the `run_all` script.
So it also does not interfere with the TAP protocol or anything.
However it also gives the chance to have a proper output, choosable level of parallelisms and is a more standard way. Which will also be supported by basically every IDE and allows some handy features as returning just the failed test e.g. then with verbose output.
This would allow us also to have a cleaner test output in the CI as well as a better overview which test do what. Currently in my opinion that's a bit messy with the 4000 lines output of the `run_all -v`.

**Comment by djmitche** [comment]
CTest sounds very appealing!  I don't think this PR will make implementing that any more difficult, and I've found it pretty useful in a few other PRs (and in fact have accidentally pushed a cherry-pick of this PR a few times now!) so I'll merge this.

Let's get an issue or PR filed to consider a switch to CTest.

**Comment by felixschurk** [comment]
Yes sounds like a good plan to me, I will pick it up on Tuesday :)

**Pull request merged**
