### PR TITLE
replace several loops with std::copy

### PR DESCRIPTION
**Pull request by neheb**
std::copy is usually faster and works the same as push_back underneath.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by tbabej** [comment]
Do we know for a fact this is a valid performance improvement? My gut tells me this should be basically the same (as the `std::copy` will translate to roughly the same code it replaces), and anecdotal evidence sees to suggest so: https://hjortsberg.org/notes/C++-vector-insert-performance.html

**Comment by neheb** [comment]
Based on godbolt testing, std::copy is better since it avoids having to call reserve. It's also a one liner.

**Comment by tbabej** [comment]
Let's not do this for now, with C++20 ranges we should have more readable way of doing accomplishing the same. When it comes to performance improvements, according to the profiling information these codepaths are not critical.

**Comment by neheb** [comment]
Maybe these could be replaced with the insert method instead.

**Pull request closed without merging**
