### PR TITLE
Fix test suite for Python 3.9

### PR DESCRIPTION
**Pull request by tbabej**
This upgrades the test runner to support Python 3.9, mostly by replacing deprecated methods with their new equivalents.

Also updates the Copyright across the repo to 2020, thus fixing one more `version.t` test :slightly_smiling_face:

### CODE REVIEW

**Comment by mrossinek** [comment]
Should we rebase this fix on the 2.5.2 branch?

**Comment by pbeckingham** [comment]
Yes, we want this on 2.5.2 and 2.6.0. Then we release 2.5.2.

**Comment by tbabej** [comment]
Rebasing might turn into too many conflicts (a lot of search-and-replace happening in this PR), but I can open an analogue of this PR for the 2.5.2 branch.

**Comment by tbabej** [comment]
Pushed to 2.5.2 directly to spare some review cycles (commits 720c561b75e687d87dc683b924a37295224a7811 to 351965a87bda9cbe633b5904a6618aebd6382fb0).

**Pull request merged**
