### PR TITLE
Refactor task diffs to handle new attributes

### LINKED ISSUE #2572: taskDifferences needs to handle `tag_` attributes properly
Longer-term, when we represent task changes as operations, this function can just describe the queued operations.

Until then, it looks at the attributes in tasks, and is currently not doing the right thing for `tag_`.  #2569 will leave the same problem for `dep_`.

### PR DESCRIPTION
**Pull request by djmitche**
This refactors task(Info)Differences to be methods of Task and to
correctly handle the `annotation_`, `tags_`, and `dep_` attributes.

Fixes #2572.

#### Additional information...

- [x] Have you run the test suite?

### CODE REVIEW

**Comment by djmitche** [comment]
@tbabej ping

**Comment by tbabej** [comment]
I'm actually looking at this right now!

**Review by tbabej — APPROVED** [review]
This looks great, and I love the refactorings included (both `isAnnotationAttr` and the `diff` methods on the `Task` objects are making things definitely much cleaner).

I tested the generated diff output and it works as expected, even when pushed hard with migration scenarios between 2.5.3 and 2.6.0:

```
[warrior@pr-2589s taskwarrior]$ task2.5.3 add tagtest +old1
Created task 1.
[warrior@pr-2589s taskwarrior]$ task2.5.3 1 mod -old1 +old2
Modifying task 1 'tagtest'.
Modified 1 task.
[warrior@pr-2589s taskwarrior]$ task 1 mod +new1
Modifying task 1 'tagtest'.
Modified 1 task.
Filter: ( ( ( id == 1 ) ) )
[warrior@pr-2589s taskwarrior]$ task 1 mod -new1 +new2
Modifying task 1 'tagtest'.
Modified 1 task.
Filter: ( ( ( id == 1 ) ) )
[warrior@pr-2589s taskwarrior]$ task 1 info

Name          Value                                        
ID            1                                            
Description   tagtest                                      
Status        Pending                                      
Entered       2021-09-04 14:35:53 (43s)
Last modified 2021-09-04 14:36:26 (10s)                    
Tags          new2 old2
Virtual tags  LATEST ORPHAN PENDING READY TAGGED UNBLOCKED 
UUID          96c86453-be9f-4b13-934a-ad6d152fcb07
Urgency        0.9                                         

    tags    0.9 *    1 =    0.9
                         ------
                            0.9

Date                Modification       
2021-09-04 14:36:08 Tag 'old1' deleted.
                    Tag 'old2' added.  
2021-09-04 14:36:17 Tag 'new1' added.
2021-09-04 14:36:26 Tag 'new1' deleted.
                    Tag 'new2' added.  
```

Same works for depends:

```
[warrior@pr-2589s taskwarrior]$ task2.5.3 add deptask 
Created task 2.
[warrior@pr-2589s taskwarrior]$ task2.5.3 add deptask2
Created task 3.
[warrior@pr-2589s taskwarrior]$ task2.5.3 3 mod depends:1,2
Modifying task 3 'deptask2'.
Modified 1 task.
[warrior@pr-2589s taskwarrior]$ task2.5.3 3 mod depends:-1
Modifying task 3 'deptask2'.
Modified 1 task.

[warrior@pr-2589s taskwarrior]$ task 3 mod depends:-2
Modifying task 3 'deptask2'.
Modified 1 task.

[warrior@pr-2589s taskwarrior]$ task 3 mod depends:1,2
Modifying task 3 'deptask2'.
Modified 1 task.

[warrior@pr-2589s taskwarrior]$ task 3 info

Name                 Value                               
ID                   3                                   
Description          deptask2                            
Status               Pending                             
This task blocked by 1 tagtest
                     2 deptask
Entered              2021-09-04 14:38:19 (32s)           
Last modified        2021-09-04 14:38:49 (2s)
Virtual tags         BLOCKED LATEST ORPHAN PENDING       
UUID                 6bf6edb3-f117-4323-ac30-56262e5eb81a
Urgency                -5                                

    blocked      1 *   -5 =     -5
                            ------
                                -5

Date                Modification                                                 
2021-09-04 14:38:36 Dependency on '96c86453-be9f-4b13-934a-ad6d152fcb07' added.  
                    Dependency on 'fb9763e0-e20d-4e17-a116-b74be97a598f' added.  
2021-09-04 14:38:40 Dependency on '96c86453-be9f-4b13-934a-ad6d152fcb07' deleted.
2021-09-04 14:38:46 Dependency on 'fb9763e0-e20d-4e17-a116-b74be97a598f' deleted.
2021-09-04 14:38:49 Dependency on '96c86453-be9f-4b13-934a-ad6d152fcb07' added.
                    Dependency on 'fb9763e0-e20d-4e17-a116-b74be97a598f' added.
```

**Comment by tbabej** [comment]
@djmitche The only remaining issue of similar nature is the `task edit`, which identifies `tag_*` and `dep_*` attributes as orphan UDAs:

```
$ task 3 edit 
...

# User Defined Attribute Orphans 
  UDA Orphan dep_96c86453-be9f-4b13-934a-ad6d152fcb07: x 
  UDA Orphan dep_fb9763e0-e20d-4e17-a116-b74be97a598f: x 
```

This should be a quick fix for the `Task::getUDAOrphanUUIDs` method, I can fix that one :slightly_smiling_face:

**Comment by djmitche** [comment]
Thanks!  I've re-run CI since I think the failure was intermittent.  I can merge when that's green.

**Comment by tbabej** [comment]
@djmitche unfortunately I suspect the CentOS7 failures are not intermittent. I've seen it fail consistently in couple of previous MRs, for example [here](https://github.com/GothenburgBitFactory/taskwarrior/pull/2576/checks). I'm not sure what prevents git on CentOS7 from checking out the submodule version properly, but at this point I'm inclined to just disable testing of TW on that platform.

However, for some reason the github-workflows still try to execute configurations that I've already disabled on the target branch (for example, debian stable was failing with intermittent error, and the PR here still expects it to start running).

Perhaps @liskin knows what could be going on here with the Github not respecting the workflow configuration on the target/source branch?

**Comment by tbabej** [comment]
CentOS 7 build failed again and Debian stable is stuck. Forcing the merge.

**Comment by liskin** [comment]
@tbabej Sure, I can take a look, but I haven't seen any mention of Debian stable in any of the runs around here. What am I missing? Can you point me to the failing workflow run?

**Comment by tbabej** [comment]
@liskin Ah, I see the confusion - the Github UI hides the pending status checks once the PR is merged. You can check the situation on the ongoing PR that I just opened here: https://github.com/GothenburgBitFactory/taskwarrior/pull/2595

You will notice that both CentOS7 and Debian Testing checks are pending (and will not start). Those have been removed from the test matrix on the 2.6.0 some time ago, and hence are not part of the matrix defined either on the source or the target branch of the PR.

Note that this only happens for the `pull-request` check category, the `push` (executed on individual commits) behaves as expected.

**Comment by liskin** [comment]
Oh, I see. Somewhere in https://github.com/GothenburgBitFactory/taskwarrior/settings/branches is (probably) says "Choose which status checks must pass before branches can be merged into a branch that matches this rule.", so you may need to update that to reflect the current checks.

(I've never used branch protection rules so I don't actually know what it looks like or whether one can just tell it to require all checks, but this seems like the most likely explanation.)

**Comment by tbabej** [comment]
Arrgh, yes, that was it!! Thanks for the right pointer. I modified the list and even all the past MRs that I forced merged are showing correctly as green :slightly_smiling_face: thank you!

image

**Pull request merged**
