### PR TITLE
use the (existing) .cargo/audit.toml to ignore some rust advisories

### PR DESCRIPTION
**Pull request by djmitche**
I was grepping for `RUSTSEC` and realized we had ignores set up already, but they had ended up in `taskchampion/.cargo` instead of `.cargo`.  Let's see if the GH actions pass for this PR..

### CODE REVIEW

**Comment by djmitche** [comment]
It does!  So we don't actually need the forked action.

**Comment by tbabej** [comment]
Nice! I suppose that means we can archive the audit-rs repo?

**Review by tbabej — APPROVED** [review]

**Comment by djmitche** [comment]
There's some question about people still using it, or moving it somewhere more official, so let's hold off on that.

**Comment by pinkforest** [comment]
psst we've forked - https://github.com/rustsec/audit-check

psssst it's sometimes helpful to have runtime flag support instead of having to rely on some config file in-repo

**Comment by djmitche** [comment]
True!  Would you like me to propose the same PR to the new "upstream"?

I'll archive the repo in this org.

**Pull request merged**
