### PR TITLE
Un-wait a waiting task when done

### PR DESCRIPTION
**Pull request by mrossinek**
#### Description

Implements #2322 

The unittest mirrors the `TestFeature608.test_done_stop` method in `start.t`.

#### Additional information...

- [x] Have you run the test suite?

### CODE REVIEW

**Comment by mrossinek** [comment]
@tbabej Given your recent activity I noticed I still have this pending PR. I don't know why the CI never ran for this though and I cannot retrigger it.. Would you mind giving it a review as is? If you have some comments a further commit should trigger the CI again :+1:

**Comment by tbabej** [comment]
I wonder if we want this behaviour also for `task delete`?

**Comment by mrossinek** [comment]
> I wonder if we want this behaviour also for `task delete`?

@tbabej I extended the fix to `DeleteCommand` as well :+1:

**Review by tbabej — APPROVED** [review]
Looks good to me!

**Pull request merged**
