### PR TITLE
Scheduled attribute updated in handleRecurrence.

### PR DESCRIPTION
**Pull request by scompo**
Hi, I'm using the scheduled attribute in a recurring task, and noticed it's not updated when creating the next task.

I think it's a known problem, and related to #1534.

#### Description

I've handled the `scheduled` attribute in the same way of `wait` when handling the recurrence.
Just added the difference from the original `due` and `scheduled` to the new `due` date as the `scheduled`.

#### Additional information...

- I've modified the C++ code but I'm not able to build the code on aarch64, so I haven't tested it.

### CODE REVIEW

**Comment by tbabej** [comment]
@scompo This looks good on my end. Do you think you could add support for the `until` attribute as well? That way we'd fully address the issue in #1534.

As far as the build failure on `aarch64`, could you perhaps open up a separate issue about that? We are striving to support multiple architectures, including this one.

**Comment by scompo** [comment]
@tbabej Sure, I'll look into updating the `until` flag too. From the documentation it looks like it should be updated the same as both `wait` and `scheduled`. Anything else I should worry about it when upgrading it?

As for for the compilation problem I'll open up a new issue with the error as soon as I'm able to

**Comment by djmitche** [comment]
@tbabej do you remember the status here? Was this worthwhile merging without the `until` support?

**Comment by djmitche** [comment]
I'm going to close this as stale. It's still here and can be re-opened!

**Comment by ashprice** [comment]
Hmm. In addition to the ongoing interative tasks development, I was wondering if a temporary fix would be desired, maybe just merging the `scheduled`-related commits? (I'd be happy to take a look at them and merge them relative to any changes needed since this PR was closed, though I'm a bit of git noob so I'm not sure of the 'technically correct' way to maintain commit history referring to @scompo.)

For `until` - is it actually desired that, pending iterative tasks landing, that we want an until date to be such that until is `current_task_until = current_task_due + (original_template_until - original_template_due)`? 

Because I actually find the current way where `current_task_until = original_template_until` to be _more_ intuitive, whatever the original documentation suggested. 

The iterative RRULES will handle both cases elegantly I think, but changing `until` for recurring tasks at this point might be undesirable, because it could break the workflows of those who aren't using hooks to address this (and for those who are using hooks to address this, it will break their hooks.) 

It seems people have different ideas about this, cf. discussion at https://github.com/GothenburgBitFactory/taskwarrior/issues/1534#issuecomment-883496041. I don't really mind myself, though the lack of an `until` working how it currently does would make a `runtil` a necessity. 

But debate about what we should do with `until` is little reason to not fix `scheduled`. Of course, it would still break hooks that people are using to address it, but it's already in kind of a weird place, where `wait` is fixed but `scheduled` is not.

**Comment by djmitche** [comment]
Yeah, updating `scheduled` makes sense and is unlikely to break things. I agree that `until` is debatable and in that case it's best to not change existing functionality.

Once we have config in the replica, we could potentially add config for things like this so that people can configure it how they'd like.

**Pull request closed without merging**
