### PR TITLE
A more thorough fix to corruption of the depends property

### LINKED ISSUE #2689: Invalid json in export on some distributions
Running `task xxxx export` on two different installationes (debian and gentoo) with the same version (2.6.1) produced invalide json on gentoo (`…,"depends":["["yyy"]"],…`) while doing correct on debian (`…,"depends":["[\"yyy\"]"],…`).

I checked the patches applied on debian side but they does not show anything that would expect that differences.

### PR DESCRIPTION
**Pull request by djmitche**
This follows on to #2714, capturing the test cases @bradyt brought up and applying a more thorough approach to cleansing the corruption.

### CODE REVIEW

**Comment by bradyt** [comment]
@djmitche Are you not checking some small example with a testing account on a remote server or localhost?

Is there anyway to write a unit test that simulates and detects the breakage?

With the above commit, I see the following in ~/.task/pending.data:

```
[dep_[\"11111111-1111-1111-1111-111111111111\"]:"x" depends:"&open;\\\"11111111-1111-1111-1111-111111111111\\\"&close;" description:"foo" entry:"1609459200" modified:"1609459200" status:"pending" uuid:"00000000-0000-0000-0000-000000000000"]
[description:"foo" entry:"1609459200" modified:"1609459200" status:"pending" uuid:"11111111-1111-1111-1111-111111111111"]
```

And the following in `task export`:

```
[
{"id":1,"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000","depends":["11111111-1111-1111-1111-111111111111","[\"11111111-1111-1111-1111-111111111111\"]"],"urgency":-3},
{"id":2,"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111","urgency":10}
]
```

I am curious, if you remove anything that's not hex or comma, wouldn't that make `&open; ==> e` and `&close; ==> ce`?

**Comment by djmitche** [comment]
Hm, maybe the parsing that I'm working on isn't used by the sync process?  This has a unit test, after all :)

Let me see if I can get a manual test case running.

**Comment by djmitche** [comment]
That appears to be the case -- so I'll need to dig deeper into how/where this is getting parsed.

**Comment by djmitche** [comment]
Ugh, I'm a fool -- it's in a "JSON" format from the server.

**Comment by djmitche** [comment]
OK, I'll have a better fix -- basically the same thing but in parseJSON.

I'm just having trouble getting the tests to pass -- there seems to be a lot of context to set up.

**Comment by djmitche** [comment]
OK, I ended up just moving the tests to a new test script, as they were interfering with other tests in `test/t.t`.

I tested this by creating a set of three tasks, one depending on the other two, and syncing that to freecinc.  I could then repeatably start with an empty taskdata, sync from the server, and see the issue: `rm -rf /tmp/t1/* && TASKDATA=/tmp/t1 ./src/task sync && cat /tmp/t1/pending.data`

Before:
```
TASKDATA override: /tmp/t1
Syncing with freecinc.com:53589
     add e08e35fa-e42b-4de0-acc4-518fca8f6365 'prereq-1'
     add 92a40a34-37f3-4785-8ca1-ff89cfbfd105 'prereq-2'
     add 4b1173c5-b420-49bc-a35e-b92286b99659 'thing'
  modify 4b1173c5-b420-49bc-a35e-b92286b99659 'thing'

Sync successful.  4 changes downloaded.
[description:"prereq-1" entry:"1642461141" modified:"1642461141" status:"pending" uuid:"e08e35fa-e42b-4de0-acc4-518fca8f6365"]
[description:"prereq-2" entry:"1642461142" modified:"1642461142" status:"pending" uuid:"92a40a34-37f3-4785-8ca1-ff89cfbfd105"]
[dep_[\"92a40a34-37f3-4785-8ca1-ff89cfbfd105\":"x" dep_\"e08e35fa-e42b-4de0-acc4-518fca8f6365\"]:"x" depends:"&open;\\\"92a40a34-37f3-4785-8ca1-ff89cfbfd105\\\",\\\"e08e35fa-e42b-4de0-acc4-518fca8f6365\\\"&close;" description:"thing" entry:"1642461146" modified:"1642461151" status:"pending" uuid:"4b1173c5-b420-49bc-a35e-b92286b99659"]
```
After:
```
TASKDATA override: /tmp/t1
Syncing with freecinc.com:53589
     add e08e35fa-e42b-4de0-acc4-518fca8f6365 'prereq-1'
     add 92a40a34-37f3-4785-8ca1-ff89cfbfd105 'prereq-2'
     add 4b1173c5-b420-49bc-a35e-b92286b99659 'thing'
  modify 4b1173c5-b420-49bc-a35e-b92286b99659 'thing'

Sync successful.  4 changes downloaded.
[description:"prereq-1" entry:"1642461141" modified:"1642461141" status:"pending" uuid:"e08e35fa-e42b-4de0-acc4-518fca8f6365"]
[description:"prereq-2" entry:"1642461142" modified:"1642461142" status:"pending" uuid:"92a40a34-37f3-4785-8ca1-ff89cfbfd105"]
[dep_92a40a34-37f3-4785-8ca1-ff89cfbfd105:"x" dep_e08e35fa-e42b-4de0-acc4-518fca8f6365:"x" depends:"92a40a34-37f3-4785-8ca1-ff89cfbfd105,e08e35fa-e42b-4de0-acc4-518fca8f6365" description:"thing" entry:"1642461146" modified:"1642461151" status:"pending" uuid:"4b1173c5-b420-49bc-a35e-b92286b99659"]
```

**Comment by bradyt** [comment]
Awesome, I ran my ad-hoc Docker image, and the round trip data seems to look good now.

```
# cat .task/pending.data 
[dep_11111111-1111-1111-1111-111111111111:"x" dep_22222222-2222-2222-2222-222222222222:"x" depends:"11111111-1111-1111-1111-111111111111,22222222-2222-2222-2222-222222222222" description:"foo" entry:"1609459200" modified:"1642511753" status:"pending" uuid:"00000000-0000-0000-0000-000000000000"]
[description:"foo" entry:"1609459200" modified:"1609459200" status:"pending" uuid:"11111111-1111-1111-1111-111111111111"]
[description:"foo" entry:"1609459200" modified:"1609459200" status:"pending" uuid:"22222222-2222-2222-2222-222222222222"]
```

```
# task export
[
{"id":1,"description":"foo","entry":"20210101T000000Z","modified":"20220118T131553Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000","depends":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"urgency":-3},
{"id":2,"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111","urgency":10},
{"id":3,"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"22222222-2222-2222-2222-222222222222","urgency":10}
]
```

**Comment by djmitche** [comment]
@tbabej I apologize for getting this wrong in my last PR.  Hopefully this makes amends :)

**Review by tbabej — APPROVED** [review]
Well, if anything, the blame rests on the shoulders of the reviewer (me). The code in this new solution looks good to me (the character filtering mechanism is in particular clever, nice approach!).

**Comment by djmitche** [comment]
Should we get a release shipped that includes this change?  I've been careful to not used dependencies until it's fixed but .. it's getting hard :)

**Pull request merged**
