### PR TITLE
Implement non-cumulative config option for burndown command

### LINKED ISSUE #1914: [TW-1901] Non-cumulative burndown report
_Joel Ostblom on 2017-03-11T22:08:34Z says:_ 

 As per https://answers.tasktools.org/questions/4915614/non-cumulative-burndown-report, I think it would be useful to display non-cumulative burndown charts.

I mostly use `burndown.daily` and while the current report is already very useful, it would be well complemented by a non-cumulative report, which would facilitate identifying peaks and trends in the amount of tasks created and completed each day or week. With the cumulative report it becomes difficult to notice when here is just a few additions/completions since they are contrasted with all the tasks ever added/completed. E.g. with around 50 tasks done and pending, it is difficult to see the impact I get from completing 1 extra task today, but that extra task would seem more important if I was only comparing it with what I did yesterday.

The new cumulative behavior would still be the default and the non-cumulative version could be added by appending `.nc` to the existing burndown reports, e.g. `burndown.daily.nc`.

### PR DESCRIPTION
**Pull request by DanielMowitz**
#### Description

This should fix #1914

#### Additional information...

- [x] Have you run the test suite?

Output before implementing the feature and according test:

```bash
Failed:
template.t                          2

Unexpected successes:

Skipped:
dependencies.t                      1
export.t                            1
feature.default.project.t           4
filter.t                            1
hooks.on-modify.t                   1
import.t                            1
nag.t                               5
recurrence.t                        1
template.t                          3
tw-1999.t                           2
wait.t                              1

Expected failures:
dependencies.t                      3
filter.t                            3
hyphenate.t                         1
lexer.t                             4
quotes.t                            1
template.t                          1
tw-2124.t                           1
```

Output after implementation:
```bash
Failed:
template.t                          2

Unexpected successes:

Skipped:
dependencies.t                      1
export.t                            1
feature.default.project.t           4
filter.t                            1
hooks.on-modify.t                   1
import.t                            1
nag.t                               5
recurrence.t                        1
template.t                          3
tw-1999.t                           2
wait.t                              1

Expected failures:
dependencies.t                      3
filter.t                            3
hyphenate.t                         1
lexer.t                             4
quotes.t                            1
template.t                          1
tw-2124.t                           1
```

### CODE REVIEW

**Comment by DanielMowitz** [comment]
After fixing some (rather embarrassing) errors in the newly added test the output of test/problems now reads:
```bash
Failed:
template.t                          2
version.t                           1

Unexpected successes:

Skipped:
dependencies.t                      1
export.t                            1
feature.default.project.t           4
filter.t                            1
hooks.on-modify.t                   1
import.t                            1
nag.t                               5
recurrence.t                        1
template.t                          3
tw-1999.t                           2
wait.t                              1

Expected failures:
dependencies.t                      3
filter.t                            3
hyphenate.t                         1
lexer.t                             4
quotes.t                            1
template.t                          1
tw-2124.t                           1
```

**Comment by tbabej** [comment]
Hi @DanielMowitz, sorry for the delayed review. I found some (likely unintentional) behaviour - it looks like in the non-cumulative mode, the done tasks are not properly displayed:

image

**Comment by tbabej** [comment]
@DanielMowitz thanks for the fix!

**Review by tbabej — APPROVED** [review]
Works as advertised.

**Pull request merged**
