### PR TITLE
taskchampion: update docs

### PR DESCRIPTION
**Pull request by ryneeverett**
Aside: I see in GothenburgBitFactory/taskwarrior#2742 that deploying the developer docs to github-pages was also planned but doesn't seem to have been done. Not sure that needs to happen in this PR but seems like ultimately tying these into one documentation hierarchy -- at least by links -- would be desirable. `rust-and-c++.md` seems like a natural entrypoint into the taskchampion docs as they currently stand.

#### Description

- update CI branch filters so workflows actually run on merge
- update CI docs deployment target
- update links
- fix typos
- remove references to `ta` cli which was removed

#### Additional information...

- [ ] I changed C++ code or build infrastructure.
  Please run the test suite and include the output of `cd test && ./problems`.

- [ ] I changed Rust code or build infrastructure.
  Please run `cargo test` and address any failures before submitting.

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
Hi @ryneeverett!  Thanks for this!  There's definitely a lot of work to do to integrate the two further.  I'm focused on getting the code landed now [see discussion here](https://github.com/GothenburgBitFactory/taskwarrior/discussions/3031).  To be honest, it's way more work than I have time for!

It looks like the check failure is just an apt download flake.

**Comment by ryneeverett** [comment]
Ah. I had seen that but I wrongly assumed that work had already been merged. I'm interested in hacking on taskchampion but the rust changes in your add-rust branch are pretty minimal so I would suppose I'm unlikely to run into substantial merge conflicts.

**Comment by djmitche** [comment]
Indeed, I've tried to upstream things when possible, and for the rust changes that was possible.

You've probably seen the taskchampion label? https://github.com/GothenburgBitFactory/taskwarrior/labels/taskchampion?  GothenburgBitFactory/taskchampion#373 is assigned to me but might be a good "harder" task to look at.  Most of the rest are about ffi and build systems, so maybe not as interesting?

**Comment by ryneeverett** [comment]
I'm a total rust newbie just trying to get my hands dirty. Maybe you could take a look at GothenburgBitFactory/taskwarrior#3047 and tell me if I'm totally off track from what you were intending?

**Pull request merged**
