### PR TITLE
fixed rendering of countdown columns

### PR DESCRIPTION
**Pull request by sebu06**
Fixed countdown column counting in the wrong direction, see #1840 

- [x] Have you run the test suite?
Passed:                          2717
Failed:                             0
Unexpected successes:               0
Skipped:                            0
Expected failures:                  4
Runtime:                         0.38 seconds

### CODE REVIEW

**Comment by tbabej** [comment]
@sebu06 Looks like the `tests/columns.t.cpp` needs to be adjusted. Perhaps you did not re-run `make test` before running tests? Some of the tests are C++-based and need to be recompiled.

**Review by tbabej — CHANGES_REQUESTED** [review]
Looks good to me otherwise. Once the tests are adjusted, we can merge. Also, we'd need to document the change properly, see this [pull request](https://github.com/GothenburgBitFactory/taskwarrior/pull/2537) for inspiration :slightly_smiling_face:

**Comment by sebu06** [comment]
I just squashed the commits and forece pushed them to the branch in order to keep the log clean after merging.

**Review by tbabej — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
