### PR TITLE
Fix failing tests on 2.6.0 branch

### PR DESCRIPTION
**Pull request by mrossinek**
#### Description

This PR attempts to fix some more of the failing tests on the 2.6.0 branch.

#### Additional information...

This is part of the discussion in #2345:
- ~`filter.t`:~ will be addressed on 2.5.2 branch
- ~`project.t`:~ will be addressed on 2.5.2 branch
- ~`search.t`:~ will be addressed on 2.5.2 branch
- [x] `undo.t`: After bisecting I found this commit to be the one which introduced the problem: https://github.com/GothenburgBitFactory/taskwarrior/commit/48dff115c2d237e0c94b97a868d81360358c460e. The problem occured from an unsafe creation of a `Task` object because the `prior` string can be empty.
- [x] `version.t`: Addressed in #2343

### CODE REVIEW

**Comment by pbeckingham** [comment]
Excellent. Can you move this ver to hte 2.5.2 branch, which is the one going out first, and in most need?

**Comment by mrossinek** [comment]
Ah yes that would make sense. I noticed that #2343 is addressed at branch 2.6.0 which is why I did the same for this PR.
I will open a new PR for branch 2.5.2 as the Undo command is not broken there. But the following failures are observed on that branch:
```
Failed:
diag.t                              1
filter.t                            5
project.t                           3
search.t                            1
version.t                           1
wait.t                              1
```

I will see about addressing the individual failures and also see whether we can backport some fixes from the 2.6.0 branch (as some appear to be fixed there).
We can definitely apply #2343 on the 2.5.2 branch, though!

**Comment by pbeckingham** [comment]
This:
    Task old = Task ();

Should be:
    Task old;

**Comment by mrossinek** [comment]
I fixed the remaining issues by clarifying the need for escaping filters correctly (note in man-page as well as fixing the unittests).
I also marked all remaining issues as expected failures. They should be fixed by closing the respective issues.

However, PR #2305 added some new unittests which also fail. We should clarify some comments over there and afterwards I believe that this PR is ready to go.

**Comment by tbabej** [comment]
This is a great start, I'll try to pull the last strings together.

**Pull request merged**
