### PR TITLE
Draft: Custom virtual tag

### PR DESCRIPTION
**Pull request by pianocomposer321**
This PR adds a new feature, custom virtual tags. They can be specified in the config like so:

```
virtualtag.FORTODAY.filter=planned.before:tomorrow
```

Then they can be used like any other virtual tag, and the filter will be applied, e.g. `task +FORTODAY` will do the exact same thing as `task planned.before:tomorrow`. This is especially useful because you can use these tags in urgency settings as well:

```
urgency.user.tag.FORTODAY.coefficient=2.0
```

In this way you can effectively give all tasks that match a filter a boost in urgency.

I believe this would satisfy https://github.com/GothenburgBitFactory/taskwarrior/issues/174, and possibly others.

I have not written documentation yet, I didn't want to put in that work before I knew whether this feature would even be accepted. This is also my first contribution, so I may need a little help in learning the lay of the land ;-).

### CODE REVIEW

**Comment by djmitche** [comment]
Were the changes to `tc/rust/Cargo.log` intentional?

**Comment by djmitche** [comment]
(I don't have an opinion on the core of this PR -- I was flagged for review due to the tc/rust changes :) )

**Comment by pianocomposer321** [comment]
> Were the changes to `tc/rust/Cargo.log` intentional?

No...I'm not sure how those changes came about. Is that file edited automatically with make or anything like that?

In any case, I can remove the changes...should I just add a new commit, or somehow edit a previous one. Sorry I'm not a git expert, so I'm not sure what the right thing is to do to revert a mistake like that lol...

**Comment by djmitche** [comment]
You can just add a new commit to undo those changes.

**Comment by pianocomposer321** [comment]
Ok, so I noticed that there was a problem with my implementation, and I'm running into some issues trying to solve it.

Basically the way I'm testing whether a given task passes a filter is by adding the filter to the end of the arguments and then re-parsing the arguments. This was the only way I could see it being done in the rest of the codebase, and the `Filter` object seems to be designed around this method. The problem is that the filter is not removed from the arg list afterwards (and I didn't see an easy way to do this), which means that the argument list is being appended to permanently every time a task is checked for a custom virtual tag, which leads to unexpected results, as it affects the filter for everything.

So my question is this: is there a better way to check if a task is included in an arbitrary filter (the filter being a string of text that would be passed as an argument, like `scheduled.before:today+4d` or similar)?

**Review by djmitche — COMMENTED** [review]
(deferring review to @tbabej)

**Pull request closed without merging**
